### ISSUE TITLE
Add citation to TEV dashboard 📖

### ISSUE THREAD

**Issue by kassyray** [GBADsInformatics/TEVDashboard#18]
From Peggy: 

I got another question; would it be possible to provide a link in the meta data of the TEV dashboard to our manuscript as the source for analytical basis for this dashboard? Here are the details:
 
Schrobback, P., Dennis, G., Li, Y., Mayberry, D., Shaw, A., Knight-Jones, T., . . . Herrero, M. (2023). Approximating the global economic (market) value of farmed animals. Global Food Security, 23, 100722. doi: https://doi.org/10.1016/j.gfs.2023.100722

**Comment by kassyray** [comment]
@Schrobback do you want this in the description at the top of the dashboard? 


![Image](https://github.com/GBADsInformatics/TEVDashboard/assets/44474665/b83fa9b2-2324-4fd2-a2ca-cf26f10c0445)

**Comment by Schrobback** [comment]
@kassyray - I don't mind where we put the citation as long as it is somewhere on the TEV dashboard. I thought it would be best to add it to the metadata but if you think this is not the right place then I would follow your suggestion.

**Comment by Schrobback** [comment]
@kassyray - The description on top looks good. Should we add "Details on the methodology is available from Schrobback et al. (2023): <<< add doi >>>"

**Comment by kassyray** [comment]
That's a great idea. Looking at the metadata tabs they are also outdated so I will address that as well

**Comment by kassyray** [comment]
Added a few more issues in response to this thread.

**Comment by kassyray** [comment]
@Schrobback if you are happy with this we can close this issue https://gbadske.org/dashboards/tev/

<img width="1431" alt="image" src="https://github.com/GBADsInformatics/TEVDashboard/assets/44474665/89debb13-11d4-46c7-b679-424428fd5da4">

**Comment by kassyray** [comment]
Citation is added! 
<img width="1468" alt="image" src="https://github.com/GBADsInformatics/TEVDashboard/assets/44474665/18e48181-5ee9-429c-bf54-d6cef1495988">

**Comment by kassyray** [comment]
@Schrobback if you are happy with this we can close this issue?

**Comment by Schrobback** [comment]
@kassyray - It looks good. Let's leave it like that. Thanks Kassy!
