### ISSUE TITLE
External access to code & documentation

### ISSUE THREAD

**Issue by Schrobback** [GBADsInformatics/TEVDashboard#21]
@kassyray - I'm planning to include a link to TEV GitHub space and was wondering if we should put the code & documentation, e.g., how to information, in a separate folder for external access. What is your option on that?

**Comment by kassyray** [comment]
@Schrobback Great idea! You actually have a github repo already, but it was made private somewhere along the way. @amardeep-1 is going to address this. He was going to email you back, but discussing on this thread might be easier. 

Do you have Gabriel's updated code? The bitbucket link he provided in the email requires a log in. I'll let @amardeep-1 take it from here!

**Comment by Schrobback** [comment]
@kassyray and @amardeep-1 - I'll check that with Gabriel. He should have access now to the GBADS GitHub, right?

**Comment by amardeep-1** [comment]
This is the repo https://github.com/GBADsInformatics/TEVProject I see [Gabriel](https://github.com/denn173) as a contributor but I don't see @denn173 in https://github.com/orgs/GBADsInformatics/people so that's why it may not be visible. Let me know and I'll see if I can add Gabriel to the GitHub GBADsInformatics org.

**Comment by Schrobback** [comment]
Hi @amardeep-1, Gabriel - @denn173 - left the GBADS PPS team in 2022 and may have therefore been removed from the GBADs GitHub as a contributor. He is still working for CSIRO and helps with any follow-up work for TEV project. I think it is ok to provide him access, given that we need the latest R code and the updated documentation from him for the TEV work. Please add @denn173, at least temporarily. Thank you.

**Comment by amardeep-1** [comment]
Sent an invite to @denn173, once accepted the repo should be there.

**Comment by denn173** [comment]
> Sent an invite to @denn173, once accepted the repo should be there.

Hi @amardeep-1, 

Would it be OK if you checked at what level I was given organisational access?
I don't seem to have push permissions to the [TEVProject](https://github.com/GBADsInformatics/TEVProject) repo.

One thing to note, is  not the original repo that this code  was located in, that was the [PPSTheme](https://github.com/GBADsInformatics/PPSTheme) repo.

However, I thought it would be better to push the code to   [TEVProject](https://github.com/GBADsInformatics/TEVProject) repo, as it has been abandoned, and this code originally was located only in a branch of the [PPSTheme](https://github.com/GBADsInformatics/PPSTheme) repo.

Cheers.

**Comment by kassyray** [comment]
@denn173 I just gave you write access to the repo. @amardeep-1 is waiting to hear back to see if we can just make the repo public. Let us know here if you have any issues with access. 

I agree that the TEVProject (main branch) is probably the most appropriate place for this code. I'm not sure what was in there before though? I think maybe a data comparison project that was de-prioritized? We would love it if you could also update the readme accordingly :)

**Comment by denn173** [comment]
> @denn173 I just gave you write access to the repo. @amardeep-1 is waiting to hear back to see if we can just make the repo public. Let us know here if you have any issues with access.
> 
> I agree that the TEVProject (main branch) is probably the most appropriate place for this code. I'm not sure what was in there before though? I think maybe a data comparison project that was de-prioritized? We would love it if you could also update the readme accordingly :)

Hi @kassyray ,  and @Schrobback 

I have added all the code and data here:  https://github.com/GBADsInformatics/TEVProject, so everything should be up to date, including the `README.md`. 

Yes, the original repository was the location of a de-prioritised data comparison project.
I have overwritten the history of the original repo.

I don't have any issues with the making the repository public, are there no issues you see with doing that @Schrobback ?
I have squashed the repo history, so  there should not be any privacy concerns.

**Comment by Schrobback** [comment]
@denn173 - Thank you for transferring the latest files! As part of the technical guide for the TEV calculation we need to provide the R code. 
@kassyray - Once we published this, it would be interesting to monitor how often these files are accessed/downloaded. Users need to have a decent understanding about R to make sense of this, just wondering how useful the technical guides, including R code will actually be.

**Comment by Schrobback** [comment]
@kassyray - Which link should I use in the technical guide document for access to the public GitHub repository?

**Comment by kassyray** [comment]
@Schrobback I'm not sure how we would monitor that, I've never done anything like that but I can talk to Deb and see if anyone has the bandwidth to explore whether this is possible and if so, if it can be set up.

Regarding the link in the technical guide my assumption would be the TEV project repo - @amardeep-1 have you heard back about whether this can be opened up?

**Comment by Schrobback** [comment]
@kassyray - Monitoring the number of downloads from the repo was only an idea to track the extent to which the technical guide will be used. This is not critical but I thought at least worth a consideration.

 @amardeep-1 - Please let me know about which public link to the TEV project repo I can use in the technical guide document.

**Comment by Schrobback** [comment]
Hi @kassyray, @amardeep-1 and @denn173, I saw that there is a public repo folder available now called 'TEVDashboard', I'm not entirely sure if that is the one intended for public sharing in the TEV technical guide document, e.g., code & data used for the manuscript which Gabriel shared. We only need to share the code (clean version used in the manuscript), data sources and some documentation (something similar to the introduction for the private folder "TEVProject"). I don't think the information in the current public folder 'TEVDashboard' reflects that. Could you please all check that? I'm happy to arrange a quick call to further clarify what is needed. Let me know.

**Comment by kassyray** [comment]
Hi @Schrobback https://github.com/GBADsInformatics/TEVProject has just been made public. Apologies for the delay! 
We wouldn't want to put all the data and code in the same repo as TEVDashboard because it would increase the cost of storing the Docker container that is used to deploy the dashboard to the server (more data = larger container = larger cost).

Let me know if you need to arrange a meeting or call - I typically am working on GBADs Thursdays and Fridays unless there is something pressing.

**Comment by Schrobback** [comment]
Hi @kassyray, The new public folder is looking good! THANK YOU! I'll have a more detailed look at the content in the next days (e.g., some of the comments in the R code may need to be removed) but I think the current information is all that is needed for external user to have a look and play.

**Comment by kassyray** [comment]
Hi @Schrobback no problem! Gabriel is the one that populated, I just clicked the button to make it public. 

I'm glad that it's all coming together 😊
